SchedulingWebApp/Pages/Home/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Collections.Generic;
using SchedulingWebApp.Data.Model;
using SchedulingWebApp.Controllers.API;
using Dapper;


namespace SchedulingWebApp.Pages.Home;

public class IndexModel(ILogger<IndexModel> logger, DatabaseAPI databaseAPI) : PageModel
{

    private readonly ILogger<IndexModel> _logger = logger;
	private readonly DatabaseAPI _api = databaseAPI;

    //private static ViewModel viewModel = new ViewModel();

    private static List<Course>? courses = new List<Course>();
    private static List<Major> major = new List<Major>();
    public static List<int> codesInt = new List<int>();

//put saved model with major picked
    

    public void fillNewMajorModel() {
        foreach(Major elem in _api.getCachedMajors()) {
            if(!major.Contains(elem)){
                major.Add(elem);
            }
        }
    }

    public void fillCoursesList(int majorId) {
        List<int> courseIds = _api.FetchCoursesFromMajor(majorId);

        foreach (int elem in courseIds){
            if(!courses.Contains(_api.FetchCourse(elem))){
            courses.Add(_api.FetchCourse(elem));
            }
        }
    }


    public PartialViewResult OnGetCoursesPartial() {
        return new PartialViewResult
        {
            ViewName = "_CoursesPartial",
            ViewData = new ViewDataDictionary<List<Course>>(ViewData, courses),
        };
    }


	public PartialViewResult OnGetMajorsPartial() {
        major = new List<Major>();
        fillNewMajorModel();
        return new PartialViewResult
        {
            ViewName = "_MajorsPartial",
            ViewData = new ViewDataDictionary<List<Major>>(ViewData, major)
        };
    }
    
    
//make it a fucking cookie and find that in a cookie.
//2 am, May-8: didn't need a cookie :)

    public void OnPostSubmitMajor() {
        string id = Request.Form["major"];
        int major = Int32.Parse(id ?? "0");
        
        // _logger.LogInformation("In post submit major. " + major);
        // _logger.LogInformation("In post submit major. ID: " + id);
        courses = new List<Course>();
        fillCoursesList(major);
    }

    
    public void OnPostSubmitCourses() {
        string codeString = Request.Form["selected"];
        List<string> codesString = codeString.Split(new char[] { ',' }).ToList();
        _logger.LogInformation("In Post Courses " + codeString);
        _logger.LogInformation("List of codes " + codesString.Count());

        foreach (var code in codesString) {
            int codeInt = Int32.Parse(code ?? "0");
            codesInt.Add(codeInt);
        }


    }

}

SchedulingWebApp/Pages/Shared/_CoursesPartial.cshtml
@model IEnumerable<SchedulingWebApp.Data.Model.Course>

@{
    Layout =null;
}

    <div class="modal fade" id="coursesModal" asp-page-handler="CoursesPartial" tabindex="-1" role="dialog">
        <div class="partialBody modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title">Select Courses:</h1>
                    <button id="coursesClosePopUp" type="button" class="closeModal" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    @if (Model != null){
                        <p>Please select all courses that you have already taken and/or have credits for:</p>
                        <form method="post" class="containSelect" asp-page-handler="SubmitCourses">
                            <ul id="courses" name="courses">
                                @foreach(var elem in Model){
                                    <label>
                                        <input type="checkbox" name="selected" value="@elem.CourseID"/>
                                        @elem.CourseCode @elem.CourseName 
                                    </label>
                                }
                            </ul> 
                            <div class="modal-footer">
                                <input class ="btn-save" type="submit" value="Send" onsubmit="setTimeout(function() {window.location.reload(); }, 10)"/>
                            </div>
                        </form>
                    } else {
                        <p>Uh oh, you haven't selected a major!</p>
                    }
                </div>
                @* <div class="modal-footer">
                    @if (Model != null){
                        <button id="coursesSave" class="btn" data-save="modal">Save</button>
                    }
                </div> *@
            </div>
        </div>
    </div>

@* <script>
    $('#coursesClosePopUp').click(function(){
        $('#coursesPartial').hide();
    })
</script> *@

    @*
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"> </script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#coursesPopUp").click(function() {
                $("coursesPartial").modal('show');
            });
            $("#coursesClosePopUp").click(function(){
                $("coursesPartial").modal('hide');
            });
        });
    </script>
    *@

SchedulingWebApp/Pages/Shared/_Layout.cshtml
@using SchedulingWebApp.Controllers
@using Microsoft.AspNetCore.Mvc.Routing;
@using Microsoft.AspNetCore.Mvc.TagHelpers;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    <title>@ViewData["Title"] - SchedulingApplication</title>
    <link rel="stylesheet" 
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
          crossorigin="anonymous">
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> 
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>

<body>
    <div class="layout">
        <nav class=" navbar contain">
            <div class="container">
                <a href="../Home/Index"><img class="logo" src="~/images/ITShielfTransparent.png"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">  </span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" href="../Home/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="../CourseTree/Index">Course Tree</a>
                        </li>
                        @if (ViewData["Title"] == "Course Tree"){
                        <li class="nav-item">
                            <button id="majorsPopUpBtn" class="nav-btn" data-toggle="ajax-modal" data-url="@Url.Page("Index", "MajorsPartial")">Major</button>
                        </li>
                        <li class="nav-item">
                            <button id="coursesPopUpBtn" class="nav-btn" data-toggle="ajax-modal" data-url="@Url.Page("Index", "CoursesPartial")">Courses</button>
                        </li>
                        }
                        @* <li class="nav-item">
                            <a class="nav-link" href="../Privacy">Privacy</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>

        @* Content *@
        <div class="main contain">  
            <div class="overlay" id="coursesPartial"></div>
            <div class="overlay" id="majorsPartial"></div>
            @RenderBody()
        </div>
    </div>

    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js" 
            crossorigin="anonymous"></script>
    <script 
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
            crossorigin="anonymous"></script>
    <script 
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
            crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @* Footer  *@
    @* <div class="border-top footer ">
        <div>
            &copy; 2024 - SchedulingWebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </div> *@


    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

SchedulingWebApp/Pages/Shared/_MajorsPartial.cshtml
@model IEnumerable<SchedulingWebApp.Data.Model.Major>

@{
    Layout =null;
}

    <div class="modal fade" id="majorsModal" asp-page-handler="MajorsPartial" tabindex="-1" role="dialog" area-labelledby="pickMajor">
        <div class="partialBody modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title">Select Major:</h1>
                    <button type="button" id="majorsClosePopUpBtn" class="close" data-dismiss="modal" area-label="Close">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Please select your major below:</p>
                    @* <form asp-page-handler="MajorsPartial" class="containSelect" method="post"> *@
                    <form method="post" class="containSelect" asp-page-handler="SubmitMajor">
                        <select id="major" name="major">
                            @foreach (var major in Model){
                                <option type="text" value="@major.Id" name="@major.Id">@major.major</option>
                            }
                            
                            @* @foreach (var view in Model){
                                @foreach (var major in view){
                                <option type="text" value="@major.majors.Id" name="@major.Id">@major.major</option>
                            }} *@
                        </select>
                        <div class="modal-footer">
                            <input class ="btn-save" type="submit" value="Send" onclick="setTimeout(function() {window.location.reload(); }, 10)"/>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    @* <button id="majorSave" class="btn-save" data-save="modal" type="submit" value="submit" asp-page-handler="SubmitMajor">Save</button> *@
                </div>
            </div>
        </div>
    </div>